Update PARTICIPANTS.MD
camaraproject/Governance pull request #114
Opened 2023-12-14 09:24 UTC by philipxujin

Add Xu Jin from Huawei into PARTICIPANTS.MD

2023-12-14 09:53 UTC, hdamker requested changes
@philipxujin please join the mailing list of CAMARA as a first step
all+subscribe@lists.camaraproject.org
As soon this is done we can approve and merge this PR.
--


[all+subscribe@lists.camaraproject.org](mailto:all+subscribe@lists.camaraproject.org)

2023-12-15 02:07 UTC, philipxujin commented
@hdamker Done, I received Welcome Group Notification email from all@lists.camaraproject.org today, thanks!

2023-12-15 07:06 UTC, MarkusKuemmerle approved these changes
Jin Xu (Philip) has joined the mailing list

2023-12-18 17:54 UTC, hdamker approved these changes

2023-12-18 17:54 UTC, merged