Create CreateNewRepository.md
camaraproject/Governance pull request #115
Opened 2023-12-19 13:34 UTC by MarkusKuemmerle

2024-01-29 11:12 UTC, hdamker reviewed
See two necessary corrections. Beyond that I recommend to move the file to "SupportingDocuuments" (just edit the file name for that).

2024-01-29 11:12 UTC, hdamker commented on documentation/CreateNewRepository.md
> +	* Insert value for §api_family_abbreviation§ and a description (following the pattern of the existing Subgroups)
```suggestion
	* Insert value for "sp-§api_family_abbreviation§" and a description (following the pattern of the existing Subgroups)
```

2024-01-29 11:12 UTC, hdamker commented on documentation/CreateNewRepository.md
> +  * Select button "Add rule" and repeat it with pattern "*release*"
```suggestion
  * Select button "Add rule" and repeat it with pattern "\*release\*"
```

2024-03-28 08:53 UTC, hdamker requested changes
We discussed in admin team to move the content into [wiki.camaraproject.org](https://wiki.camaraproject.org) => don't merge here.

@wrathwolf can you please confirm when this is done so we can close the PR here?

2024-04-25 10:27 UTC, MarkusKuemmerle commented
Content is moved into the Wiki

2024-04-25 10:27 UTC, closed without merging