Update ProjectCharter.md - Adjust license rule for Marketing Working Group
camaraproject/Governance pull request #127
Opened 2024-04-20 16:03 UTC by MarkusKuemmerle

2024-04-21 16:10 UTC, hdamker requested changes
LGTM, one typo

2024-04-21 16:10 UTC, hdamker commented on ProjectCharter.md
> +- Only exception is the documentation contributed to or created by the Outreach Committee (former Marketing Working Group) in the reoository [https://github.com/camaraproject/Marketing](https://githu
```suggestion
- Only exception is the documentation contributed to or created by the Outreach Committee (former Marketing Working Group) in the repository [https://github.com/camaraproject/Marketing](https://github.com/camaraproject/Marketing). For that the [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by/4.0/legalcode.txt) shall apply. It is strongly forbidden to save any API-related definition, documentation or code in this repository.
```

2024-04-21 16:35 UTC, hdamker commented
@MarkusKuemmerle Please add a description of the PR and a link to the issue. Otherwise it is difficult to understand later why this PR happened.

2024-04-22 06:28 UTC, MarkusKuemmerle commented
Working Groups are seperated in different repos. Links have to be adjusted.
See https://github.com/camaraproject/Governance/issues/84.

2024-04-22 06:29 UTC, hdamker approved these changes

2024-04-22 10:09 UTC, merged